server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:htpt_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:htpt_secret_2026}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.htpt.common.event"
        spring.json.use.type.headers: false

logging:
  level:
    com.htpt.notification: INFO
